-- extends "projects/small.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Optimizers"
    -- set ns.config_description = "Compare optimizer performance"

    ## https://arxiv.org/pdf/2507.07101
    ## beta2 is optimal for beta2_batch_size token batch-size
    -- set ns.beta2 = 0.999

[globals]
    == super()
    ## https://arxiv.org/pdf/2507.07101
    ## Scale beta2 to have constant half-life
    -- set ns.scaled_beta2 = ns.beta2 ** (ns.tokens_per_step / ns.base_batch_size)

[variable_listing]
    == super()
# ns.base_lr: {{ ns.base_lr }}
# ns.scaled_beta2: {{ ns.scaled_beta2 }}