-- extends "meta_defaults.yaml"

[configs]
name: "Wikitext BPE Tokenizer"
description: "An example BPE tokenizer trained on the 'EleutherAI/wikitext_document_level' dataset"
config_prefix: "configs"
default_config: "32k.yaml"
