-- extends "test/test_type.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Eval: C4"
    -- set ns.config_description = "Evaluate on the packed allenai/c4 (en) test split"
    -- set ns.eval_name = "c4"

[main_body]
    == super()
    dataset_proj: "{{ abspath(joinpath(ns.forgather_dir, "examples", "datasets", "allenai")) }}"
    dataset_config: "en.yaml"