-- extends "test/test_type.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Eval: OpenAssistant"
    -- set ns.config_description = "Evaluate on the packed OpenAssistant test split"
    -- set ns.eval_name = "openassistant"

[main_body]
    == super()
    dataset_proj: "{{ abspath(joinpath(ns.forgather_dir, "examples", "datasets", "OpenAssistant")) }}"
    dataset_config: "openassistant_packed.yaml"