# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bulk.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'bulk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbulk.proto\x12\x10\x66orgather.diloco\"\x15\n\x05\x43hunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x13GlobalParamsRequest2\xf0\x01\n\nDiLoCoBulk\x12H\n\x10SubmitPseudograd\x12\x17.forgather.diloco.Chunk\x1a\x17.forgather.diloco.Chunk(\x01\x30\x01\x12\x46\n\x0eSubmitFragment\x12\x17.forgather.diloco.Chunk\x1a\x17.forgather.diloco.Chunk(\x01\x30\x01\x12P\n\x0cGlobalParams\x12%.forgather.diloco.GlobalParamsRequest\x1a\x17.forgather.diloco.Chunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bulk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNK']._serialized_start=32
  _globals['_CHUNK']._serialized_end=53
  _globals['_GLOBALPARAMSREQUEST']._serialized_start=55
  _globals['_GLOBALPARAMSREQUEST']._serialized_end=76
  _globals['_DILOCOBULK']._serialized_start=79
  _globals['_DILOCOBULK']._serialized_end=319
# @@protoc_insertion_point(module_scope)
