# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bulk_pb2 as bulk__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bulk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiLoCoBulkStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitPseudograd = channel.stream_stream(
                '/forgather.diloco.DiLoCoBulk/SubmitPseudograd',
                request_serializer=bulk__pb2.Chunk.SerializeToString,
                response_deserializer=bulk__pb2.Chunk.FromString,
                _registered_method=True)
        self.SubmitFragment = channel.stream_stream(
                '/forgather.diloco.DiLoCoBulk/SubmitFragment',
                request_serializer=bulk__pb2.Chunk.SerializeToString,
                response_deserializer=bulk__pb2.Chunk.FromString,
                _registered_method=True)
        self.GlobalParams = channel.unary_stream(
                '/forgather.diloco.DiLoCoBulk/GlobalParams',
                request_serializer=bulk__pb2.GlobalParamsRequest.SerializeToString,
                response_deserializer=bulk__pb2.Chunk.FromString,
                _registered_method=True)


class DiLoCoBulkServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitPseudograd(self, request_iterator, context):
        """Pseudo-gradient submission (full model). Request chunks carry the framed
        [len][header][blob]; response chunks carry the framed averaged weights.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitFragment(self, request_iterator, context):
        """Streaming-DiLoCo per-fragment submission. Same framing; the header carries
        fragment_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalParams(self, request, context):
        """Fetch the current global parameters (no request body, like the HTTP GET).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiLoCoBulkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitPseudograd': grpc.stream_stream_rpc_method_handler(
                    servicer.SubmitPseudograd,
                    request_deserializer=bulk__pb2.Chunk.FromString,
                    response_serializer=bulk__pb2.Chunk.SerializeToString,
            ),
            'SubmitFragment': grpc.stream_stream_rpc_method_handler(
                    servicer.SubmitFragment,
                    request_deserializer=bulk__pb2.Chunk.FromString,
                    response_serializer=bulk__pb2.Chunk.SerializeToString,
            ),
            'GlobalParams': grpc.unary_stream_rpc_method_handler(
                    servicer.GlobalParams,
                    request_deserializer=bulk__pb2.GlobalParamsRequest.FromString,
                    response_serializer=bulk__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgather.diloco.DiLoCoBulk', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgather.diloco.DiLoCoBulk', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiLoCoBulk:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitPseudograd(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/forgather.diloco.DiLoCoBulk/SubmitPseudograd',
            bulk__pb2.Chunk.SerializeToString,
            bulk__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitFragment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/forgather.diloco.DiLoCoBulk/SubmitFragment',
            bulk__pb2.Chunk.SerializeToString,
            bulk__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forgather.diloco.DiLoCoBulk/GlobalParams',
            bulk__pb2.GlobalParamsRequest.SerializeToString,
            bulk__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
