-- extends "meta_defaults.yaml"

-- block configs
name: "Open-Orca Finetune"
description: "Finetune a model on the Open-Orca reasoning dataset (packed)"
config_prefix: "configs"
default_config: "llama3_1b/1gpu_default.yaml"
<< endblock configs
