-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Singlehead Small"
    -- set ns.config_description = "Single-head ALiBi transformer (attention + MLP), ~24M params"
    -- set ns.model_name = model_name | default("singlehead_small")

[model_definition]
    -- include "config.small.model"

#------------- config.small.model --------------
-- extends "project.model"

[model_config]
    == super()
    hidden_size: {{ hidden_size | toyaml(512) }}
    num_hidden_layers: {{ num_hidden_layers | toyaml(8) }}
    intermediate_size: {{ intermediate_size | toyaml(1280) }}
