-- extends "meta_defaults.yaml"

[configs]
name: "Tiny Stories BPE Tokenizer"
description: "An example BPE tokenizer trained on the Tiny Stories dataset"
config_prefix: "configs"
default_config: "2k.yaml"
