-- extends "datasets/load_packed_dataset.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "C++ Code Large"
    -- set ns.config_description = "Large synthetic C++ code dataset by Feynman Innovations"
    -- set ns.source = "https://huggingface.co/datasets/ajibawa-2023/Cpp-Code-Large"
    -- set ns.main_feature = "code"

[load_dataset_args]
    == super()
    path: "ajibawa-2023/Cpp-Code-Large"

[train_dataset_split]
    == super()
    split: "train[10000:]"

[validation_dataset_split]
    == super()
    split: "train[0:1000]"

[test_dataset_split]
    == super()
    split: "train[1000:10000]"
