-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.tokenizer_name = tokenizer_name | default("wikitext_2k_32K")
    -- set ns.config_name = "Wikitext 2K 32K"
    -- set ns.config_description = "2K BPE tokenizer, trained on Wikitext, with 32K context"
    -- set ns.vocab_size = vocab_size | default(2000)
    -- set ns.model_max_length = model_max_length | default(32768)
