-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Single-Head + MLP (small)"
    -- set ns.config_description = "Single-head ALiBi transformer with the MLP sub-block (~24M params)"
    -- set ns.model_name = "mlp_small"
    -- set ns.model_project_dir = joinpath(ns.forgather_dir, 'examples', 'models', 'singlehead')
    -- set ns.model_project_config = "small.yaml"

[model_constructor_args]
    == super()
    attn_implementation: "eager"
