-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Adafacttor"
    -- set ns.config_description = "Adafactor baseline, for comparison"
    -- set ns.log_name = log_name | default("adafactor")
    -- set ns.lr = lr | default(5e-4)

[optimizer]
optimizer: &optimizer !partial:forgather.ml.optim.adafactor:Adafactor
    lr: {{ ns.lr | toyaml }}
    use_triton: True