-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Adam"
    -- set ns.config_description = "Adam baseline, for comparison"
    -- set ns.log_name = log_name | default("adam")
    -- set ns.lr = lr | default(5e-4)

[optimizer]
optimizer: &optimizer !partial:torch:optim.AdamW
    lr: {{ ns.lr | toyaml }}
    weight_decay: 0.0
    fused: True