-- extends "configs/adafactor-like.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "AF SinkGD 1-step"
    -- set ns.config_description = "Adafactor-like implementation of sr-sinkhorn with 1-step"
    -- set ns.log_name = log_name | default("ada-sinkgd-1")

[sinkgd]
    == super()
    num_iters: 1
