-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Factored"
    -- set ns.config_description = "SinkGD normalize via Adafactor-like approach"
    -- set ns.log_name = log_name | default("factored")

[sinkgd]
    == super()
    mode: "factored"