-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Unified SinkGD LR=0.03"
    -- set ns.config_description = "Learning rate 0.03"
    -- set ns.log_name = log_name | default("lr-03")
    -- set ns.lr = 0.03
