-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "SinkGD Momentum"
    -- set ns.config_description = "SinkGD with momentum=0.9"
    -- set ns.log_name = log_name | default("momentum")
    -- set ns.momentum = 0.9
