-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "SinkGD"
    -- set ns.config_description = "Baseline SingGD implementation"
    -- set ns.log_name = log_name | default("paper")

[optimizer]
    [sinkgd]
.define: &sinkgd !partial:forgather.ml.optim.sinkgd:SinkGD
    lr: {{ ns.sinkgd_lr | toyaml }}
    num_iters: {{ ns.num_iters | toyaml }}
    normalize_output: {{ ns.normalize_output | toyaml }}

    [multiopt]
optimizer: &optimizer !partial:forgather.ml.optim.multiopt:make_re_multiopt
    optimizer_map:
        - [ "embed|lm_head|norm|bias", "adam" ]
        - [ ".*", "sinkgd" ]
    factories:
        sinkgd: *sinkgd
        adam: !partial:torch.optim:Adam
            lr: {{ ns.lr | toyaml }}
            weight_decay: !!float 0.0
    debug: True