-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "SinkGD"
    -- set ns.config_description = "Baseline SingGD implementation"
    -- set ns.log_name = log_name | default("paper")

[optimizer]
optimizer: &optimizer !partial:forgather.ml.optim.sinkgd:SinkGD
    lr: {{ (0.02 * 0.05) | toyaml }}
    num_iters: 5
    normalize_output: False

[no_decay_optim]
.define: &no_decay_optim !partial:torch:optim.AdamW
    lr: !!float 0.02

[optimizer_groups]
    == super.super()
