-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "SinkGD (sparse embed)"
    -- set ns.config_description = "SinkGD with sparse mode for embed/LM-head"
    -- set ns.log_name = log_name | default("sparse")

[sinkgd]
    == super()
    torch_compile: False

[optim_embed_grp]
    == super()
    mode: "sparse"
    lr: {{ ns.sinkgd_lr | toyaml }}