-- extends "exp.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Unified SinkGD WD=0.005"
    -- set ns.config_description = "Weight decay 0.005"
    -- set ns.log_name = log_name | default("wd-005")
    -- set ns.weight_decay = 0.005
