-- extends "configs/unified.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Unified SinkGD WD=0.001"
    -- set ns.config_description = "Weight decay 0.001"
    -- set ns.log_name = log_name | default("wd-001")
    -- set ns.weight_decay = 0.001
