import random
from enum import Enum
from functools import wraps
from typing import Any, Callable, Set, TypeVar

_F = TypeVar("_F", bound=Callable[..., Any])


class ConversionDescriptor:
    def __init__(self, cls, *, default):
        self._cls = cls
        self._default = default

    def __set_name__(self, owner, name):
        self._name = "_" + name

    def __get__(self, obj, type):
        if obj is None:
            return self._default

        return getattr(obj, self._name, self._default)

    def __set__(self, obj, value):
        setattr(obj, self._name, self._cls(value))


class DiagnosticEnum(Enum):
    @classmethod
    def _missing_(cls, value):
        raise ValueError(
            f"'{value}' is not a valid {cls.__name__}; choose one of {cls._value2member_map_.keys()}"
        )


def format_line_numbers(text: str) -> str:
    """Format a string with line-numbers"""
    return "".join(map(lambda x: f"{x[0]+1:>6}: {x[1]}\n", enumerate(text.split("\n"))))


def add_exception_notes(error: Exception, *args) -> Exception:
    """
    Add notes to an exception using the native Python 3.11+ add_note() API.
    """
    for arg in args:
        error.add_note(str(arg))
    return error


# Word lists used to build memorable names of the form "adjective-species"
# (e.g. "spectacular-fox"). AutoName enumerates the permutations to produce
# deterministic Python identifiers for generated code; generate_name() pulls a
# random pairing for human-facing labels such as DiLoCo worker names.
ADJECTIVES = [
    "abundant",
    "aero",
    "aether",
    "amber",
    "ancient",
    "arcane",
    "arctic",
    "ashen",
    "azure",
    "baroque",
    "bitter",
    "bittersweet",
    "black",
    "blazing",
    "bleak",
    "blessed",
    "blonde",
    "blue",
    "bold",
    "bracing",
    "brave",
    "brilliant",
    "bronze",
    "brown",
    "calm",
    "cascading",
    "celestial",
    "charcoal",
    "chasing",
    "cheerful",
    "clever",
    "climbing",
    "cloudy",
    "colder",
    "colossal",
    "cool",
    "copper",
    "coral",
    "cosmic",
    "crimson",
    "crisp",
    "curious",
    "cursed",
    "dancing",
    "daring",
    "dark",
    "dashing",
    "deep",
    "defending",
    "delicate",
    "discovering",
    "divine",
    "dread",
    "drift",
    "dusk",
    "eager",
    "ebony",
    "effervescent",
    "elegant",
    "elemental",
    "elusive",
    "ember",
    "emerald",
    "enchanted",
    "enigma",
    "eternal",
    "ethereal",
    "exploring",
    "fabled",
    "faerie",
    "faint",
    "fate",
    "fathom",
    "fathomless",
    "fierce",
    "fiery",
    "finding",
    "flicker",
    "flying",
    "frost",
    "frozen",
    "gale",
    "gentle",
    "ghost",
    "giant",
    "glacial",
    "gliding",
    "gloaming",
    "glyph",
    "golden",
    "gossamer",
    "graceful",
    "grand",
    "green",
    "gregarious",
    "grey",
    "grimoire",
    "grumpy",
    "guarding",
    "hallowed",
    "happy",
    "haunting",
    "haven",
    "hazy",
    "hidden",
    "hollow",
    "holly",
    "holy",
    "huge",
    "humble",
    "hunting",
    "hushed",
    "icy",
    "illuminated",
    "immense",
    "immortal",
    "incantation",
    "indigo",
    "inferno",
    "infinite",
    "iron",
    "ivory",
    "jade",
    "jagged",
    "jasper",
    "jet",
    "jinxed",
    "jolly",
    "jovial",
    "joyful",
    "joyous",
    "jubilant",
    "kaleidoscope",
    "keen",
    "kenotic",
    "khaki",
    "kinetic",
    "knotty",
    "lavender",
    "lavish",
    "leaping",
    "light",
    "lilac",
    "liminal",
    "little",
    "lively",
    "loud",
    "loyal",
    "luminous",
    "lunar",
    "magenta",
    "magical",
    "magnetic",
    "maroon",
    "massive",
    "mellow",
    "merry",
    "micro",
    "mighty",
    "miniature",
    "misty",
    "murky",
    "mystic",
    "mystical",
    "mythic",
    "navy",
    "nebula",
    "nebulous",
    "nimble",
    "noble",
    "nocturnal",
    "nostalgic",
    "numberless",
    "obsidian",
    "occult",
    "oceanic",
    "ochre",
    "odd",
    "old",
    "omen",
    "onyx",
    "opalescent",
    "opulent",
    "orange",
    "ornate",
    "parched",
    "parchment",
    "passionate",
    "pearl",
    "petite",
    "phantom",
    "placid",
    "potion",
    "powerful",
    "prismatic",
    "protecting",
    "proud",
    "pure",
    "purple",
    "quaint",
    "quaking",
    "quartz",
    "questing",
    "quick",
    "quiet",
    "quixotic",
    "racing",
    "radiant",
    "raging",
    "rainy",
    "rare",
    "red",
    "resplendent",
    "riddle",
    "riding",
    "roaming",
    "rose",
    "ruby",
    "rugged",
    "runic",
    "rusted",
    "sable",
    "sacred",
    "sailing",
    "saving",
    "scarlet",
    "seeking",
    "sepia",
    "serene",
    "shadow",
    "sharp",
    "shimmering",
    "silent",
    "silver",
    "singing",
    "small",
    "smoldering",
    "snowy",
    "soaring",
    "soft",
    "solemn",
    "spell",
    "star",
    "steel",
    "storm",
    "stormy",
    "sunny",
    "sweet",
    "swift",
    "swimming",
    "sylvan",
    "tall",
    "tart",
    "tawny",
    "teal",
    "tempest",
    "temple",
    "tender",
    "tidal",
    "tiny",
    "towering",
    "tranquil",
    "true",
    "turbulent",
    "ultra",
    "unbroken",
    "undulating",
    "unfathomable",
    "unique",
    "unseen",
    "unyielding",
    "vast",
    "veil",
    "veiled",
    "velvet",
    "vermilion",
    "vibrant",
    "violet",
    "vivid",
    "void",
    "wandering",
    "wanderlust",
    "ward",
    "warm",
    "whispering",
    "white",
    "wild",
    "windy",
    "wise",
    "wish",
    "wistful",
    "woven",
    "wraith",
    "xenial",
    "yearless",
    "yearning",
    "yellow",
    "yonder",
    "young",
    "youthful",
    "zealous",
    "zephyr",
    "zinnia",
]


SPECIES = [
    "acouchi",
    "addax",
    "albatross",
    "alligator",
    "alpaca",
    "anaconda",
    "anemone",
    "angelfish",
    "anglerfish",
    "anole",
    "ant",
    "anteater",
    "antelope",
    "anura",
    "ape",
    "aphid",
    "arapaima",
    "archerfish",
    "argus",
    "armadillo",
    "asp",
    "avocet",
    "axolotl",
    "babirusa",
    "baboon",
    "badger",
    "baleen",
    "bandicoot",
    "banshee",
    "barbel",
    "barracuda",
    "bass",
    "beagle",
    "bear",
    "beaver",
    "bee",
    "beetle",
    "beluga",
    "bengal",
    "bilby",
    "binturong",
    "bison",
    "blacktip",
    "blenny",
    "bluejay",
    "bluetongue",
    "boa",
    "bobcat",
    "bobwhite",
    "bonito",
    "bonobo",
    "booby",
    "brant",
    "brittlestar",
    "brocket",
    "buffalo",
    "bumblebee",
    "burro",
    "bushbaby",
    "bushpig",
    "butterfly",
    "caiman",
    "camel",
    "canary",
    "capybara",
    "caracal",
    "cardinal",
    "cardinalfish",
    "carp",
    "cassowary",
    "cat",
    "caterpillar",
    "cattle",
    "cavefish",
    "cavy",
    "centipede",
    "chaffinch",
    "chameleon",
    "chamois",
    "char",
    "charr",
    "cheetah",
    "chevrotain",
    "chickadee",
    "chicken",
    "chigger",
    "chihuahua",
    "chinchilla",
    "chipmunk",
    "chiton",
    "chub",
    "cicada",
    "civet",
    "clam",
    "cobra",
    "collie",
    "colobus",
    "condor",
    "constrictor",
    "conure",
    "cooter",
    "cormorant",
    "cougar",
    "cow",
    "coyote",
    "crab",
    "crane",
    "cricket",
    "crocodile",
    "crow",
    "cuckoo",
    "curlew",
    "dachshund",
    "deer",
    "dhole",
    "dingo",
    "doberman",
    "dodo",
    "dog",
    "dolphin",
    "dormouse",
    "dove",
    "dragon",
    "dragonfly",
    "drake",
    "duck",
    "dugong",
    "dunnock",
    "eagle",
    "echidna",
    "eel",
    "elephant",
    "elk",
    "emu",
    "ermine",
    "falcon",
    "fennec",
    "ferret",
    "finch",
    "flamingo",
    "flea",
    "flounder",
    "fly",
    "fossa",
    "fowl",
    "fox",
    "frog",
    "gargoyle",
    "gazelle",
    "gecko",
    "gerbil",
    "gerenuk",
    "gharial",
    "gibbon",
    "gila",
    "giraffe",
    "glider",
    "gnat",
    "gnu",
    "goat",
    "golem",
    "goose",
    "gopher",
    "gorilla",
    "goshawk",
    "grasshopper",
    "greyhound",
    "grouse",
    "guineafowl",
    "guineapig",
    "hammerhead",
    "hamster",
    "hare",
    "harpy",
    "harrier",
    "hawk",
    "hedgehog",
    "heron",
    "hippo",
    "hippopotamus",
    "hog",
    "hornbill",
    "horned",
    "hornet",
    "horse",
    "hound",
    "hummingbird",
    "husky",
    "hydra",
    "hyena",
    "hyrax",
    "ibex",
    "ibis",
    "iguana",
    "imp",
    "impala",
    "indri",
    "jackal",
    "jackdaw",
    "jaguar",
    "jaguarundi",
    "jay",
    "jellyfish",
    "jerboa",
    "kangaroo",
    "kingfisher",
    "kite",
    "kitsune",
    "kitten",
    "kiwi",
    "koa",
    "koala",
    "komodo",
    "kraken",
    "krill",
    "kudu",
    "labrador",
    "ladybug",
    "lamb",
    "lemming",
    "lemur",
    "leopard",
    "lion",
    "lioness",
    "lizard",
    "llama",
    "lobster",
    "locust",
    "loon",
    "loris",
    "louse",
    "lynx",
    "lyrebird",
    "macaw",
    "magpie",
    "malamute",
    "mamba",
    "mammoth",
    "manatee",
    "manta",
    "mantis",
    "marmoset",
    "marmot",
    "marten",
    "meerkat",
    "mermaid",
    "millipede",
    "mink",
    "minke",
    "minnow",
    "minotaur",
    "mole",
    "mollusk",
    "molly",
    "monarch",
    "mongoose",
    "mongrel",
    "monitor",
    "monkey",
    "monkfish",
    "moose",
    "moth",
    "mouflon",
    "mouse",
    "mule",
    "murre",
    "muskox",
    "muskrat",
    "mussel",
    "myna",
    "naga",
    "narwhal",
    "newfoundland",
    "newt",
    "nighthawk",
    "nightingale",
    "numbat",
    "nutria",
    "nymph",
    "ocelot",
    "octopus",
    "okapi",
    "onry",
    "opossum",
    "orangutan",
    "orca",
    "oryx",
    "osprey",
    "ostrich",
    "otter",
    "owl",
    "ox",
    "oxpecker",
    "oyster",
    "panda",
    "pangolin",
    "panther",
    "parakeet",
    "parrot",
    "partridge",
    "peacock",
    "pelican",
    "penguin",
    "perch",
    "pheasant",
    "pigeon",
    "pika",
    "piranha",
    "platypus",
    "plover",
    "polecat",
    "pomeranian",
    "pony",
    "porcupine",
    "porpoise",
    "possum",
    "prairiedog",
    "prawn",
    "puffin",
    "pug",
    "puma",
    "python",
    "quail",
    "quetzal",
    "quokka",
    "quoll",
    "rabbit",
    "raccoon",
    "racer",
    "radder",
    "ram",
    "rat",
    "raven",
    "ray",
    "reindeer",
    "rhea",
    "rhino",
    "ringtail",
    "robin",
    "rodent",
    "rooster",
    "ruffe",
    "rufous",
    "sabertooth",
    "sable",
    "salamander",
    "salmon",
    "sambar",
    "sandpiper",
    "sardine",
    "satyr",
    "sawfish",
    "scorpion",
    "seagull",
    "seahorse",
    "seal",
    "serpent",
    "serval",
    "shad",
    "shark",
    "sheep",
    "sheepdog",
    "shrew",
    "shrike",
    "shrimp",
    "siamang",
    "siren",
    "skunk",
    "sloth",
    "slug",
    "snail",
    "snake",
    "snipe",
    "sole",
    "sparrow",
    "spider",
    "sponge",
    "squid",
    "squirrel",
    "stag",
    "starfish",
    "starling",
    "stingray",
    "stinkbug",
    "stint",
    "stoat",
    "stork",
    "sturgeon",
    "swallow",
    "swan",
    "swift",
    "swordtail",
    "tabby",
    "tamarin",
    "tanager",
    "tapir",
    "tarantula",
    "tattler",
    "tengu",
    "termite",
    "tern",
    "terrier",
    "thrush",
    "tick",
    "toad",
    "tortoise",
    "toucan",
    "trout",
    "trumpeter",
    "tuna",
    "turkey",
    "turtle",
    "unicorn",
    "urchin",
    "viper",
    "vireo",
    "vole",
    "vulture",
    "wagtail",
    "walleye",
    "walrus",
    "warbler",
    "wasp",
    "weasel",
    "weaver",
    "weevil",
    "wels",
    "whale",
    "whelp",
    "whimbrel",
    "whippet",
    "whiptail",
    "whitefish",
    "widgeon",
    "wildcat",
    "wolf",
    "wolverine",
    "wombat",
    "woodpecker",
    "worm",
    "wraith",
    "wrasse",
    "wren",
    "wyvern",
    "yak",
    "yellowjacket",
    "zebra",
    "zebrafish",
    "zebu",
    "zokor",
    "zombie",
]


class AutoName:
    """Iterator yielding unique, valid Python identifiers.

    Names are produced by deterministically walking the Cartesian product of
    :data:`ADJECTIVES` and :data:`SPECIES`, joined and suffixed with an
    underscore, e.g. ``"abundant_acouchi_"``. This produces memorable,
    collision-resistant symbol names for generated code (see
    :class:`forgather.graph_encoder.GraphEncoder`, which assigns these to
    unnamed nodes).

    The product is large (``len(ADJECTIVES) * len(SPECIES)``); once it is
    exhausted a numeric suffix is appended so the iterator keeps producing
    unique identifiers indefinitely, e.g. ``"abundant_acouchi_1_"``.

    For random, human-facing names use :func:`generate_name` instead.
    """

    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        n_species = len(SPECIES)
        period = len(ADJECTIVES) * n_species
        i = self.i
        self.i += 1

        cycle, offset = divmod(i, period)
        adjective = ADJECTIVES[offset // n_species]
        species = SPECIES[offset % n_species]
        if cycle:
            return f"{adjective}_{species}_{cycle}_"
        return f"{adjective}_{species}_"


def generate_name(separator: str = "-") -> str:
    """Return a random memorable name of the form ``adjective<sep>species``.

    Args:
        separator: String placed between the adjective and species. Defaults
            to ``"-"``; pass ``"_"`` for an identifier-safe variant.

    Returns:
        A generated name string, e.g. ``"spectacular-fox"``.

    Unlike :class:`AutoName`, which deterministically enumerates unique Python
    identifiers for generated code, this pulls a random pairing and is intended
    for human-facing labels such as DiLoCo worker names. Note the default
    hyphen separator is *not* a valid Python identifier.
    """
    return f"{random.choice(ADJECTIVES)}{separator}{random.choice(SPECIES)}"


def track_depth(method: _F) -> _F:
    """Decorator to track the recursion depth of a class method."""

    @wraps(method)
    def wrapper(self, *args, **kwargs):
        # Increment the recursion level
        self.level += 1
        try:
            # Call the actual method
            result = method(self, *args, **kwargs)
        finally:
            # Decrement the recursion level regardless of method success
            self.level -= 1
        return result

    return wrapper  # type: ignore[return-value]


def indent_block(block, indent_level=4):
    indent = " " * indent_level
    s = "".join(map(lambda s: indent + s + "\n", block.split("\n")))
    return s[:-1]
