-- extends "projects/lm_training_project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "Experimental SinkGD"
    -- set ns.config_description = "Single SinkGD for all params"
    -- set ns.log_name = log_name | default("exp")
    -- set ns.nproc_per_node = 1

    -- set ns.lr = lr | default(0.02)
    -- set ns.sinkgd_alpha = sinkgd_alpha | default(0.05)
    -- set ns.weight_decay = weight_decay | default(0.0)
    -- set ns.normalize_output = normalize_output | default(False)
    -- set ns.momentum = momentum | default(0.0)
    -- set ns.nesterov = nesterov | default(False)
    -- set ns.num_iters = num_iters | default(1)

    ## Needed for Tiny Callbacks
    -- set ns.default_attn_implementation = attn_implementation | default("sdpa")

[globals]
    == super()
    -- set ns.sinkgd_lr = ns.lr * ns.sinkgd_alpha

[variable_listing]
    == super()
# ns.sinkgd_lr: {{ ns.sinkgd_lr }}

[trainer_args]
    == super()
    # **Optimizers**
    save_strategy: {{ save_strategy | toyaml('no') }}
    float32_matmul_precision: {{ float32_matmul_precision | toyaml("high") }}
    default_dtype: {{ default_dtype | toyaml("float32") }}
    mixed_precision: {{ mixed_precision | toyaml("bf16") }}

    # Enable compile by default, with maximum performance
    torch_compile: {{ compile | default(True) }}
    torch_compile_full_graph: True
    torch_compile_dynamic: False
-- if ns.gradient_accumulation_steps == 1
    ## This setting appears to cause issues when using gradient accumulation
    torch_compile_mode: "max-autotune"
-- endif

[optimizer]
    [sinkgd]
# The optimizer factory
# This uses the definition from the project's 'src' directory
.define: &sinkgd !partial:./src/sinkgd_exp.py:SinkGD
    lr: {{ ns.sinkgd_lr | toyaml }}
    mode: "sr_sinkhorn"
    num_iters: {{ns.num_iters | toyaml }}
    weight_decay: {{ ns.weight_decay | toyaml }}
    normalize_output: {{ ns.normalize_output | toyaml }}
    momentum: {{ ns.momentum | toyaml }}
    nesterov: {{ ns.nesterov | toyaml }}

    [optim_groups]
# This assigns optimizer groups based upon a regex on the model's FQNs
# They are searched in the order in which they are defined
.define: &optim_group_map
    - [ "norm|bias", "small" ]
    - [ "embed", "embed" ]
    - [ "lm_head", "head" ]
    - [ ".*", "dense" ]

    [optim_embed_grp]
# Overrides for embedding
.define: &optim_embed_grp
    mode: "adam"
    lr: {{ ns.lr }}

    [optim_head_grp]
# Overrides for language head
.define: &optim_head_grp
    mode: "adam"
    lr: {{ ns.lr }}

    [optim_small_grp]
# Overrides for biases and norms
.define: &optim_small_grp
    mode: "adam"
    lr: {{ ns.lr }}

    [optim_dense_grp]
# Overrides for all main transformer blocks
.define: &optim_dense_grp !dict

    [grouped_optimizer]
# Helper for building an optimizer with groups
optimizer: &optimizer !partial:forgather.ml.optim.opt_utils:make_grouped_optimizer
    optimizer_factory: *sinkgd
    group_map: *optim_group_map
    group_config:
        embed: *optim_embed_grp
        head: *optim_head_grp
        small: *optim_small_grp
        dense: *optim_dense_grp
    # Show FQN -> group mappings
    debug: True

[trainer_callbacks]
    -- include 'project.callbacks'

[dynamic_args]
    == super()
    sinkgd_alpha:
        names: "--sinkgd-alpha"
        type: float
        help: "SinkGD Alpha"
    num_iters:
        names: "--num-iters"
        type: int
        help: "Number of SinkGD iterations."
    weight_decay:
        names: "--weight-decay"
        type: float
        help: "Decoupled weight decay"
    momentum:
        names: "--momentum"
        type: float
        help: "Momentum coefficient (0 = off)"
    nesterov:
        names: "--nesterov"
        type: bool
        help: "Use Nesterov momentum"

#-------------------- project.callbacks --------------------
-- extends 'callbacks/tiny_callbacks.yaml'

[callback_list]
    == super()
    text_gen_callback: null # Disable text gen
