-- extends "projects/lm_training_project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "SinkGD"
    -- set ns.config_description = "Baseline SingGD implementation"
    -- set ns.log_name = log_name | default("sinkgd")
    -- set ns.nproc_per_node = 1

    -- set ns.lr = lr | default(0.02)
    -- set ns.sinkgd_alpha = sinkgd_alpha | default(0.05)
    -- set ns.weight_decay = weight_decay | default(0.0)
    -- set ns.normalize_output = normalize_output | default(False)
    -- set ns.momentum = momentum | default(0.0)
    -- set ns.nesterov = nesterov | default(False)

    ## Needed for Tiny Callbacks
    -- set ns.default_attn_implementation = attn_implementation | default("sdpa")

[trainer_args]
    == super()
    # **Optimizers**
    save_strategy: {{ save_strategy | toyaml('no') }}
    float32_matmul_precision: {{ float32_matmul_precision | toyaml("high") }}
    default_dtype: {{ default_dtype | toyaml("float32") }}
    mixed_precision: {{ mixed_precision | toyaml("bf16") }}

    # Enable compile by default, with maximum performance
    torch_compile: {{ compile | default(True) }}
    torch_compile_full_graph: True
    torch_compile_dynamic: False
-- if ns.gradient_accumulation_steps == 1
    ## This setting appears to cause issues when using gradient accumulation
    torch_compile_mode: "max-autotune"
-- endif

[optimizer]
    [sinkgd]
.define: &sinkgd !partial:forgather.ml.optim.sinkgd:SinkGD
    lr: {{ (ns.lr * ns.sinkgd_alpha) | toyaml }}
    num_iters: {{ num_iters | toyaml(5) }}
    normalize_output: {{ ns.normalize_output | toyaml }}

    [multiopt]
optimizer: &optimizer !partial:forgather.ml.optim.multiopt:make_re_multiopt
    optimizer_map:
        - [ "embed|lm_head|norm|bias", "adam" ]
        - [ ".*", "sinkgd" ]
    factories:
        sinkgd: *sinkgd
        adam: !partial:torch.optim:Adam
            lr: {{ ns.lr | toyaml }}
            weight_decay: !!float 0.0
    debug: True

[trainer_callbacks]
    -- include 'project.callbacks'

[dynamic_args]
    == super()
    sinkgd_alpha:
        names: "--sinkgd-alpha"
        type: float
        help: "SinkGD Alpha"
    num_iters:
        names: "--num-iters"
        type: int
        help: "Number of SinkGD iterations."
    weight_decay:
        names: "--weight-decay"
        type: float
        help: "Decoupled weight decay"
    momentum:
        names: "--momentum"
        type: float
        help: "Momentum coefficient (0 = off)"
    nesterov:
        names: "--nesterov"
        type: bool
        help: "Use Nesterov momentum"

#-------------------- project.callbacks --------------------
-- extends 'callbacks/tiny_callbacks.yaml'

[callback_list]
    == super()
    text_gen_callback: null # Disable text gen
