-- extends "project.yaml"

[config_metadata]
    == super()
    -- set ns.config_name = "FSDP2 Trainer"
    -- set ns.config_description = "Minimal FSDP2 Trainer config"
    -- set ns.log_name = "fsdp2_2gpu"
    -- set ns.nproc_per_node = 2
