-- extends "meta_defaults.yaml"

-- block configs
name: "Evaluation Configs"
description: "Named evaluation configurations for use with `forgather eval`"
config_prefix: "configs"
default_config: "tinystories.yaml"
<< endblock configs
