-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "fp8"
    -- set ns.config_description = "Train with fp8 weights"
    -- set ns.log_name = log_name | default("fp8_adamw")
    -- set ns.model_name = model_name | default("fp8_adamw")

[trainer_args]
    == super()
    mixed_precision: bf16
    default_dtype: "bfloat16"
    fp8_recipe: tensorwise

[optimizer]
optimizer: &optimizer !partial:forgather.ml.optim:AdamW
    lr: {{ ns.global_lr | toyaml }}