-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Long Cooldown"
    -- set ns.config_description = "Extended cooldown, 0.7"
    -- set ns.model_name = model_name | default("long_cooldown")

    ## Extend to 10x Chinchilla
    -- set ns.total_tokens = total_tokens | default(22700)

    ## Extend cooldown to 70% (from 30%) of token budget
    -- set ns.cooldown_p = 0.7