-- extends "project.yaml"

[config_metadata]
    == super()
    ## Overrides
    -- set ns.config_name = "Train with PP"
    -- set ns.config_description = "Experiment in training a small LM with Pipeline Parallel"
    -- set ns.model_name = model_name | default("pp")
    -- set ns.trainer_type = trainer_type | default("pipeline")

[trainer_args]
    == super()

    # max-autotune runs into issues; disable for now
    torch_compile_mode: default

[trainer_callbacks]
    -- include 'pp.logger_config'

#-------------------- pp.logger_config --------------------
-- extends 'project.logger_config'

[callback_list]
    == super()
    # Textgen is incompatible with the Pipeline Parallel trainer
    text_gen_callback: null