-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Ten Chinchilla"
    -- set ns.config_description = "10x Chinchilla + 1x Chinchilla annealing phase"
    -- set ns.model_name = model_name | default("long_cooldown")

    ## Extend to 10x Chinchilla
    -- set ns.total_tokens = total_tokens | default(24970)

[globals]
    == super()
    ## Decay for 10% of total tokens
    -- set ns.decay_steps = (ns.total_steps * 0.1) | int
    -- set ns.decay_start_step = (ns.total_steps - ns.decay_steps) | int

[lr_scheduler]
    == super()
    annealing_steps: {{ ns.decay_steps }}
    checkpoint_step: {{ ns.decay_start_step }}