-- extends 'project.yaml'

[config_metadata]
    == super()
    -- set ns.config_name = "Small Mistral"
    -- set ns.config_description = "A Mistral (Llama variant with sliding-window attention, GQA; ~34M params)"
    -- set ns.model_name = "small_mistral"
    -- set ns.model_project_dir = joinpath(ns.forgather_dir, 'examples', 'models', 'mistral')
    -- set ns.model_project_config = "small.yaml"
